### ISSUE TITLE
Different tensors size KITTI train

### ISSUE THREAD

**Issue by Salvatore-tech** [neu-vi/ezflow#239]
Hi,  
i was exploring the library when i tried to train on KITTI dataset with default configuration for RAFT and got an error that you can find in the log below about mismatching tensors size.
I'm also attaching the python script i used to run the training.
Is there something wrong in the dataloading step?
Thanks!

[kitti.py.txt](https://github.com/neu-vi/ezflow/files/9438187/kitti.py.txt)
[log.txt](https://github.com/neu-vi/ezflow/files/9438188/log.txt)

**Comment by NeelayS** [comment]
@kardevroop @prajnan93

**Comment by Salvatore-tech** [comment]
In the .py file attached the last line got trimmed and as is visible from the stack trace i called the `trainer.train()` after creating the trainer object. I also tried on Sintel dataset and the error was the same (different tensor size)

**Comment by NeelayS** [comment]
Hi @Salvatore-tech, thanks for reporting this. I've tagged the active maintainers (@prajnan93, @kardevroop). We'll look to get the issue resolved asap.

**Comment by prajnan93** [comment]
Hi @Salvatore-tech, the` crop_size=(384, 384)` for KITTI dataset is invalid. Please try again with a crop_size less than (375, 1242). The ideal crop_size for training RAFT with KITTI is `(288, 960)` and for training with SINTEL is `(368, 768)`

**Comment by Salvatore-tech** [comment]
Hi, 
thanks for the advice, sorry for reopening the issue, i modified the script with the crop_size you suggested (how do you compute it btw?) but now i have the following issue at epoch 1...
Am i missing something? 
[logOutOfRange.txt](https://github.com/neu-vi/ezflow/files/9485488/logOutOfRange.txt)

**Comment by prajnan93** [comment]
We can use a crop size that is smaller than the maximum height and width of the image. The max height and width can be checked by setting  the flag `crop = False` for any given dataset.  It should be noted that for **training** the crop size should be **divisible by 32**. The reason for this is that some feature extractor may downsample the image by 32 times during training. The [InputPadder ](https://ezflow.readthedocs.io/en/latest/api/utils/index.html) can be used during evaluation or prediction of any image size.  
____

`self.weights[i] ` does not include the scaling weights for all the feature pyramid levels for the model you are training. Please check the original paper to set the weights correctly. Also, if you are training RAFT then use [Sequence Loss](https://ezflow.readthedocs.io/en/latest/api/functional/ezflow.functional.criterion.html) instead of MultiscaleLoss.
